CREATE TABLE IF NOT EXISTS fr_user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    creator INT DEFAULT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifyer INT DEFAULT NULL,
    modify_time TIMESTAMP DEFAULT NULL,
    del_flag INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    open_id VARCHAR(255) NOT NULL DEFAULT '',
    union_id VARCHAR(255) DEFAULT NULL,
    session_key VARCHAR(255) DEFAULT NULL,
    public_open_id VARCHAR(255) DEFAULT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'ENABLE',
    auth_status VARCHAR(32) DEFAULT NULL,
    photo_auth VARCHAR(32) DEFAULT NULL,
    edu_auth VARCHAR(32) DEFAULT NULL,
    nick_name VARCHAR(20) NOT NULL DEFAULT 'test',
    head_portrait VARCHAR(255) NOT NULL DEFAULT 'test',
    birthday TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    height INT NOT NULL DEFAULT 0,
    profession VARCHAR(20) NOT NULL DEFAULT 'test',
    gender VARCHAR(10) NOT NULL DEFAULT 'MALE',
    school VARCHAR(20) NOT NULL DEFAULT 'test',
    education VARCHAR(20) NOT NULL DEFAULT 'Undergraduate',
    about_me VARCHAR(255) NOT NULL DEFAULT 'test',
    interest VARCHAR(255) NOT NULL DEFAULT 'test',
    love_requirement VARCHAR(255) NOT NULL DEFAULT 'test',
    lon VARCHAR(50) DEFAULT NULL,
    lat VARCHAR(50) DEFAULT NULL,
    city VARCHAR(20) DEFAULT NULL,
    home_town VARCHAR(255) DEFAULT NULL,
    tend_live_city VARCHAR(255) DEFAULT NULL,
    fond_tags VARCHAR(255) DEFAULT NULL,
    marriage VARCHAR(20) DEFAULT NULL,
    love_goal VARCHAR(20) DEFAULT NULL,
    emotional VARCHAR(20) DEFAULT NULL,
    annual_salary VARCHAR(20) DEFAULT NULL,
    we_chat_number VARCHAR(50) DEFAULT NULL,
    img_list CLOB DEFAULT NULL,
    id_card VARCHAR(255) DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL,
    invisible VARCHAR(32) DEFAULT NULL,
    invisible_date TIMESTAMP DEFAULT NULL,
    wait_approved_img CLOB DEFAULT NULL,
    real_photo CLOB DEFAULT NULL,
    phone VARCHAR(255) DEFAULT NULL,
    gold_balance INT NOT NULL DEFAULT 0,
    user_type VARCHAR(20) NOT NULL DEFAULT 'Normal',
    educational_type VARCHAR(20) NOT NULL DEFAULT 'FullTime',
    character_type VARCHAR(500) DEFAULT NULL,
    lately_time TIMESTAMP DEFAULT NULL,
    additional VARCHAR(255) DEFAULT NULL,
    pass_word VARCHAR(255) DEFAULT NULL,
    similarity FLOAT DEFAULT NULL,
    img_base64 CLOB DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS pay_order (
    id INT AUTO_INCREMENT PRIMARY KEY,
    creator INT DEFAULT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifyer INT DEFAULT NULL,
    modify_time TIMESTAMP DEFAULT NULL,
    del_flag INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    user_id INT NOT NULL,
    title VARCHAR(100) DEFAULT NULL,
    out_trade_no VARCHAR(100) NOT NULL,
    total_fee INT NOT NULL DEFAULT 0,
    status VARCHAR(100) NOT NULL,
    product_no INT NOT NULL DEFAULT 0,
    transaction_id VARCHAR(255) DEFAULT NULL
);